version: '3'
services:
    pgsql:
        image: 'postgres:14-alpine'
        ports:
            - '${DB_PORT:-5432}:5432'
        environment:
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - 'dbdata:/var/lib/postgresql/data'
        networks:
            - phpnetwork
        healthcheck:
            test: ["CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}"]
            retries: 3
            timeout: 5s
    nginx:
        build:
            context: .
            dockerfile: ./nginx/Dockerfile
        ports:
            - '${NGINX_PORT:-80}:80'
        volumes:
            - ./app:/var/www/html/backend:delegated
            - ./node/frontend:/var/www/html/frontend:delegated
        depends_on:
            - pgsql
            - php
            - node
        networks:
            - phpnetwork
    php:
        build:
            context: .
            dockerfile: ./php/Dockerfile
        volumes:
            - ./app:/var/www/html/backend
        ports:
            - '9000:9000'
        networks:
            - phpnetwork
        depends_on:
            - pgsql
    artisan:
        build:
            context: .
            dockerfile: ./php/Dockerfile
        container_name: artisan
        volumes:
            - ./app:/var/www/html/backend
        working_dir: /var/www/html
        depends_on:
            - pgsql
            - php
        user: laravel
        networks:
            - phpnetwork
        entrypoint: ['php', '/var/www/html/backend/artisan']
    composer:
        build:
            context: .
            dockerfile: ./php/composer/Dockerfile
        container_name: composer
        volumes:
            - ./app:/var/www/html
        working_dir: /var/www/html
        depends_on:
            - php
        user: laravel
        networks:
            - phpnetwork
        entrypoint: ['composer', '--ignore-platform-reqs']
    node:
        build:
            context: .
            dockerfile: ./node/Dockerfile
        container_name: node
        volumes:
            - ./node/frontend:/usr/src/app
        working_dir: /usr/src/app
        ports:
            - '3000:3000'
        networks:
            - phpnetwork
        depends_on:
            - php
        entrypoint: ['npm']

networks:
    phpnetwork:
        driver: bridge
volumes:
    dbdata:
        driver: local